#!/usr/bin/env python3
"""Generate index.html from index.template.html + content.md.

Edit prose in content.md (markdown links/**bold**/*italic* supported); layout and
styling live in index.template.html. Then run `python3 build.py`.

index.html is GENERATED — do not edit it directly; it gets overwritten.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
TEMPLATE = ROOT / "index.template.html"
CONTENT = ROOT / "content.md"
OUTPUT = ROOT / "index.html"

BANNER = ("<!-- GENERATED from index.template.html + content.md by build.py. "
          "Edit those and run `python3 build.py`; do not edit this file directly. -->")

LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
BOLD = re.compile(r"\*\*(.+?)\*\*")
ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")


def inline(text):
    """Render the inline-markdown subset. Raw HTML in the text passes through."""
    text = LINK.sub(r'<a href="\2">\1</a>', text)
    text = BOLD.sub(r"<strong>\1</strong>", text)
    text = ITALIC.sub(r"<em>\1</em>", text)
    return text


def parse_content(text):
    """Parse `## section` / `### key` headings into {"section.key": "prose"}."""
    fields, section, key, buf = {}, None, None, []

    def flush():
        nonlocal key, buf
        if key is not None:
            # Keep line structure (blank lines, bullets) for render(); trim ends.
            fields[f"{section}.{key}"] = "\n".join(buf).strip("\n")
        key, buf = None, []

    for line in text.splitlines():
        s = line.strip()
        if s.startswith("## "):
            flush()
            section = s[3:].strip()
        elif s.startswith("### "):
            flush()
            key = s[4:].strip()
        elif s.startswith("<!--"):
            continue
        elif key is not None:
            buf.append(line.rstrip())
    flush()
    return fields


def render(value):
    """Render a field. Single line → inline markdown. Multi-line → paragraphs
    plus `- ` bullet lists (each line still gets the inline subset)."""
    lines = value.split("\n")
    if len(lines) == 1:
        return inline(value)

    blocks, para, items = [], [], []

    def flush_para():
        if para:
            blocks.append("<p>" + "<br>".join(inline(p) for p in para) + "</p>")
            para.clear()

    def flush_list():
        if items:
            blocks.append("<ul>" + "".join(f"<li>{inline(i)}</li>" for i in items) + "</ul>")
            items.clear()

    for line in lines:
        s = line.strip()
        if s.startswith("- "):
            flush_para()
            items.append(s[2:].strip())
        elif not s:
            flush_para()
            flush_list()
        else:
            flush_list()
            para.append(s)
    flush_para()
    flush_list()
    return "\n".join(blocks)


def main():
    template = TEMPLATE.read_text(encoding="utf-8")
    fields = parse_content(CONTENT.read_text(encoding="utf-8"))

    placeholders = set(re.findall(r"\{\{([^}]+)\}\}", template))
    missing = placeholders - set(fields)
    unused = set(fields) - placeholders
    if missing:
        sys.exit(f"build: template placeholders with no content in content.md: "
                 f"{', '.join(sorted(missing))}")
    if unused:
        sys.exit(f"build: content.md fields with no placeholder in template: "
                 f"{', '.join(sorted(unused))}")

    out = template
    for key, value in fields.items():
        out = out.replace("{{" + key + "}}", render(value))
    out = out.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER, 1)

    OUTPUT.write_text(out, encoding="utf-8")
    print(f"build: wrote {OUTPUT.name} from {len(fields)} content fields")


if __name__ == "__main__":
    main()
