#!/usr/bin/env python3
"""Build the /writing section from the curated LessWrong archive.

Renders each curated post to a styled standalone HTML page under writing/, and
generates writing/index.html listing them newest-first. Stdlib only — matches the
site's zero-dependency build.

Source of truth is `writing/lesswrong/posts.json` (written by fetch_lesswrong.py),
specifically each post's **htmlBody** — LW's already-rendered, faithful HTML. We
build from htmlBody rather than the markdown export because the markdown silently
drops some footnote definitions. htmlBody is clean semantic HTML (p/h1-h3/ul/ol/
li/a/img/figure/blockquote/strong/i/sup + footnote spans), no inline styles or
scripts, so it drops straight into our .prose container and is styled by CSS.

Usage: python3 scripts/build_writing.py
"""
import html as html_lib
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
ARCHIVE = ROOT / "writing" / "lesswrong" / "posts.json"
OUT = ROOT / "writing"
HOME_TEMPLATE = ROOT / "index.template.html"

# How many posts the homepage features. Selection is recency-weighted: the N most
# recent curated posts (CURATED is maintained newest-first). build.py then renders
# index.html from the template region this fills.
HOMEPAGE_N = 4
HOME_BEGIN = ("<!-- BEGIN homepage-writing : the 4 most recent curated posts, "
              "generated by scripts/build_writing.py — do not edit by hand -->")
HOME_END = "<!-- END homepage-writing -->"

# Curated, newest-first — LW slugs.
CURATED = [
    "your-model-organisms-might-be-fried",
    "shaping-the-exploration-of-the-motivation-space-matters-for",
    "concrete-research-ideas-on-ai-personas",
    "a-case-for-model-persona-research",
    "understanding-and-controlling-llm-generalization",
    "inoculation-prompting-instructing-models-to-misbehave-at",
    "show-not-tell-gpt-4o-is-more-opinionated-in-images-than-in",
    "open-problems-in-emergent-misalignment",
    "why-i-m-moving-from-mechanistic-to-prosaic-interpretability",
    "a-sober-look-at-steering-vectors-for-llms",
    "mech-interp-lacks-good-paradigms",
]

MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

esc = lambda s: html_lib.escape(s, quote=False)
escq = lambda s: html_lib.escape(s, quote=True)


def prepare_body(html):
    """Light, safe touch-ups on LW's htmlBody — no structural rewriting."""
    # lazy-load images so long posts stay snappy
    html = re.sub(r"<img\b", '<img loading="lazy"', html)
    return html.strip()


def date_long(d):
    y, m, day = d.split("-")
    return f"{MONTHS[int(m)]} {int(day)}, {y}"


PAGE = """<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Daniel Tan</title>
    <link rel="canonical" href="{lw_url}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="../sleeper.css">
    <link rel="stylesheet" href="writing.css">
</head>
<body>
    <div class="atmos" aria-hidden="true"><div class="stars"></div><div class="lamp"></div></div>
    <div class="page">
        <div class="topbar">
            <a href="../index.html" class="wordmark">Daniel Tan</a>
            <a href="index.html" class="backlink"><span class="arr">←</span> Writing</a>
        </div>
        <header class="pagehead">
            <p class="eyebrow">{eyebrow}</p>
            <h1>{title}</h1>
            <p class="stamp">Originally on <a href="{lw_url}">LessWrong</a> · {date_long} · {karma} karma</p>
        </header>
        <article class="prose">
{body}
        </article>
        <footer class="post-foot">
            <a href="index.html" class="backlink"><span class="arr">←</span> All writing</a>
            <a href="{lw_url}">Read on LessWrong →</a>
        </footer>
    </div>
</body>
</html>
"""

INDEX = """<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Writing — Daniel Tan</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="../sleeper.css">
    <link rel="stylesheet" href="writing.css">
</head>
<body>
    <div class="atmos" aria-hidden="true"><div class="stars"></div><div class="lamp"></div></div>
    <div class="page">
        <div class="topbar">
            <a href="../index.html" class="wordmark">Daniel Tan</a>
            <a href="../index.html" class="backlink"><span class="arr">←</span> Home</a>
        </div>
        <header class="pagehead">
            <p class="eyebrow">writing</p>
            <h1>Writing</h1>
        </header>
        <p class="lede-line">Selected essays on AI safety — model personas, emergent
        misalignment, and how LLMs generalize. Originally posted on LessWrong.</p>
        <div class="writing-list">
{rows}
        </div>
        <p class="writing-more"><a href="shortform.html">Shorter notes →</a></p>
    </div>
</body>
</html>
"""


def build():
    archive = {p["slug"]: p for p in json.loads(ARCHIVE.read_text(encoding="utf-8"))}
    posts = []
    for slug in CURATED:
        if slug not in archive:
            raise SystemExit(f"curated slug not in archive: {slug}")
        p = archive[slug]
        p["title"] = (p.get("title") or "").strip()
        p["date"] = p["postedAt"][:10]
        p["out"] = f"{slug}.html"
        posts.append(p)

    for p in posts:
        y, m, _ = p["date"].split("-")
        html = PAGE.format(
            title=esc(p["title"]),
            lw_url=escq(p["pageUrl"]),
            eyebrow=f"essay · {MONTHS[int(m)]} {y}",
            date_long=date_long(p["date"]),
            karma=p["baseScore"],
            body=prepare_body(p["htmlBody"]),
        )
        (OUT / p["out"]).write_text(html, encoding="utf-8")

    rows, cur_year = [], None
    for p in posts:
        year = p["date"][:4]
        if year != cur_year:
            rows.append(f'            <div class="wyear">{year}</div>')
            cur_year = year
        mon = MONTHS[int(p["date"][5:7])]
        rows.append(
            f'            <a class="wrow" href="{escq(p["out"])}">'
            f'<span class="wdate">{mon}</span>'
            f'<span class="wtitle">{esc(p["title"])}</span>'
            f'<span class="wkarma">{p["baseScore"]} karma</span></a>'
        )
    (OUT / "index.html").write_text(INDEX.format(rows="\n".join(rows)), encoding="utf-8")

    update_homepage(posts[:HOMEPAGE_N])

    print(f"Built {len(posts)} post pages + index.html in {OUT}/")
    for p in posts:
        print(f"  writing/{p['out']}")


def update_homepage(featured):
    """Fill the homepage #writing region (in index.template.html) with the most
    recent curated posts. build.py renders index.html from the template after."""
    rows = "\n".join(
        f'                    <a href="writing/{escq(p["out"])}">\n'
        f'                        <span>{esc(p["title"])}</span>'
        f'<span class="arr">→</span></a>'
        for p in featured
    )
    tpl = HOME_TEMPLATE.read_text(encoding="utf-8")
    pat = re.compile(re.escape(HOME_BEGIN) + r".*?" + re.escape(HOME_END), re.DOTALL)
    if not pat.search(tpl):
        raise SystemExit("homepage-writing sentinels not found in index.template.html")
    block = f"{HOME_BEGIN}\n{rows}\n                    {HOME_END}"
    HOME_TEMPLATE.write_text(pat.sub(lambda _: block, tpl), encoding="utf-8")
    print(f"Updated homepage #writing with {len(featured)} most-recent posts "
          f"(re-run build.py to regenerate index.html):")
    for p in featured:
        print(f"  {p['date']}  {p['title']}")


if __name__ == "__main__":
    build()
