#!/usr/bin/env python3
"""Build the /writing section from the curated LessWrong archive.

Renders each curated post to a styled standalone HTML page under writing/, and
generates writing/index.html listing them newest-first. Stdlib only — matches the
site's zero-dependency build.

Source of truth is `writing/lesswrong/posts.json` (written by fetch_lesswrong.py),
specifically each post's **htmlBody** — LW's already-rendered, faithful HTML. We
build from htmlBody rather than the markdown export because the markdown silently
drops some footnote definitions. htmlBody is clean semantic HTML (p/h1-h3/ul/ol/
li/a/img/figure/blockquote/strong/i/sup + footnote spans), no inline styles or
scripts, so it drops straight into our .prose container and is styled by CSS.

Usage: python3 scripts/build_writing.py
"""
import html as html_lib
import json
import re
from pathlib import Path

from build_shortform import CURATED as NOTE_TITLES  # note id -> title (single source)

ROOT = Path(__file__).parent.parent
ARCHIVE = ROOT / "writing" / "lesswrong" / "posts.json"
SHORTFORM_ARCHIVE = ROOT / "writing" / "shortform" / "shortform.json"
OUT = ROOT / "writing"
HOME_TEMPLATE = ROOT / "index.template.html"

# How many posts the homepage features. Selection is recency-weighted: the N most
# recent curated posts (CURATED is maintained newest-first). build.py then renders
# index.html from the template region this fills.
HOMEPAGE_N = 4
HOME_BEGIN = ("<!-- BEGIN homepage-writing : the 4 most recent curated posts, "
              "generated by scripts/build_writing.py — do not edit by hand -->")
HOME_END = "<!-- END homepage-writing -->"

# Curated, newest-first — LW slugs.
CURATED = [
    "the-one-week-sprint",
    "your-model-organisms-might-be-fried",
    "shaping-the-exploration-of-the-motivation-space-matters-for",
    "concrete-research-ideas-on-ai-personas",
    "a-case-for-model-persona-research",
    "understanding-and-controlling-llm-generalization",
    "inoculation-prompting-instructing-models-to-misbehave-at",
    "show-not-tell-gpt-4o-is-more-opinionated-in-images-than-in",
    "open-problems-in-emergent-misalignment",
    "why-i-m-moving-from-mechanistic-to-prosaic-interpretability",
    "a-sober-look-at-steering-vectors-for-llms",
    "mech-interp-lacks-good-paradigms",
]

# The unified /writing index is organized by TOPIC, not by format. Each topic lists
# its essays and notes intermixed, newest-first, and is color-coded for the filter
# chips at the top of the page. Tuple shape: (label, slug, color, keys). Keys are
# either essay slugs (from CURATED above) or shortform comment ids (from
# build_shortform.CURATED). build() validates that every curated piece is filed under
# exactly one topic — so adding a new essay/note without assigning it here is a hard
# error, not a silent omission.
TOPICS = [
    ("AI safety research", "ai-safety-research", "#67c0b4", [
        "your-model-organisms-might-be-fried",
        "shaping-the-exploration-of-the-motivation-space-matters-for",
        "concrete-research-ideas-on-ai-personas",
        "a-case-for-model-persona-research",
        "understanding-and-controlling-llm-generalization",
        "inoculation-prompting-instructing-models-to-misbehave-at",
        "show-not-tell-gpt-4o-is-more-opinionated-in-images-than-in",
        "open-problems-in-emergent-misalignment",
        "why-i-m-moving-from-mechanistic-to-prosaic-interpretability",
        "a-sober-look-at-steering-vectors-for-llms",
        "mech-interp-lacks-good-paradigms",
        "YRcSDJxXBivZGWtzH",  # Alignment affordances of model-persona research
        "eB55D8uGASyM4ypBx",  # Functional interpretability
        "p8jEWLKfPgNMxDDQW",  # Superhuman latent knowledge
        "vKavCHHQYnqZpPvWc",  # Why anthropomorphise LLMs?
    ]),
    ("AI strategy", "ai-strategy", "#e3a94e", [
        "CuHnKee6GL8rsGaXp",  # Labs' unpublishable alignment science
        "3pSKqjZss6sKPZNDX",  # A theory of impact for research outside the labs
        "LqefzJMn7HTRthMit",  # Inference-time compute will be hard to govern
        "Dc8GytgHMn85uBiRB",  # Explaining AGI to a layperson
    ]),
    ("Research craft & automation", "research-craft", "#b89ce0", [
        "nmC7XBEZvdnjNvDmi",  # Adapting research plans on the fly
        "aYQzaxJperZFi4yc8",  # When to deduplicate work with others
        "iYsCbHJhT7CuBGvdb",  # Research engineering tips for SWEs
        "6Q7WvmD7jWoY8STHK",  # Don't write survey papers on techniques
        "4zDMdTKxKoXNt9KfJ",  # Writing papers in two phases
        "fn9YyziLj5jmBcrAJ",  # Library code vs experiment code
        "EesNATHbknuEviXDG",  # The last-mile problem in delegating to AI
        "433pv5ojHcuAWyDJu",  # Taste as a hard-to-automate skill
        "bHmNL3FAwGETAmnrD",  # Create handles for knowledge
    ]),
    ("Working & life", "working-life", "#8bbf86", [
        "the-one-week-sprint",
        "khXqEEbssMPtHTXkK",  # Fake prerequisites
        "nebMYhZvN7GXkvSyX",  # On dropping things that aren't excellent
        "zJRWriQjbEoaWW52Z",  # Learn to ask for help earlier
        "mvyWJWWzbCoiYafBX",  # Strategies in social deduction games
        "X8hzrHzpduez2DrdK",  # Writing all my notes in public
        "rv3veoLsBhdp69tLy",  # The five whys, in Todoist
        "cAc2ujatmjEYzBqsb",  # Imposter syndrome is a positive signal
    ]),
]

MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

esc = lambda s: html_lib.escape(s, quote=False)
escq = lambda s: html_lib.escape(s, quote=True)


def prepare_body(html):
    """Light, safe touch-ups on LW's htmlBody — no structural rewriting."""
    # lazy-load images so long posts stay snappy
    html = re.sub(r"<img\b", '<img loading="lazy"', html)
    return html.strip()


def date_long(d):
    y, m, day = d.split("-")
    return f"{MONTHS[int(m)]} {int(day)}, {y}"


PAGE = """<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Daniel Tan</title>
    <link rel="canonical" href="{lw_url}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="../sleeper.css">
    <link rel="stylesheet" href="writing.css">
</head>
<body>
    <div class="atmos" aria-hidden="true"><div class="stars"></div><div class="lamp"></div></div>
    <div class="page">
        <div class="topbar">
            <a href="../index.html" class="wordmark">Daniel Tan</a>
            <a href="index.html" class="backlink"><span class="arr">←</span> Writing</a>
        </div>
        <header class="pagehead">
            <p class="eyebrow">{eyebrow}</p>
            <h1>{title}</h1>
            <p class="stamp">Originally on <a href="{lw_url}">LessWrong</a> · {date_long} · {karma} karma</p>
        </header>
        <article class="prose">
{body}
        </article>
        <footer class="post-foot">
            <a href="index.html" class="backlink"><span class="arr">←</span> All writing</a>
            <a href="{lw_url}">Read on LessWrong →</a>
        </footer>
    </div>
</body>
</html>
"""

INDEX = """<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Writing — Daniel Tan</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="../sleeper.css">
    <link rel="stylesheet" href="writing.css">
</head>
<body>
    <div class="atmos" aria-hidden="true"><div class="stars"></div><div class="lamp"></div></div>
    <div class="page">
        <div class="topbar">
            <a href="../index.html" class="wordmark">Daniel Tan</a>
            <a href="../index.html" class="backlink"><span class="arr">←</span> Home</a>
        </div>
        <header class="pagehead">
            <p class="eyebrow">writing</p>
            <h1>Writing</h1>
        </header>
        <p class="lede-line">Essays and shorter notes, grouped by what they're about —
        mostly AI safety. Filter by category below. Originally posted on LessWrong.</p>
        <div class="wfilters">
{filters}
        </div>
        <div class="writing-list">
{rows}
        </div>
    </div>
    <script>
    (function () {{
      var chips = document.querySelectorAll('.wfilter');
      var groups = document.querySelectorAll('.wgroup');
      chips.forEach(function (chip) {{
        chip.addEventListener('click', function () {{
          var f = chip.getAttribute('data-filter');
          chips.forEach(function (c) {{ c.classList.toggle('is-active', c === chip); }});
          groups.forEach(function (g) {{
            g.hidden = !(f === 'all' || g.getAttribute('data-topic') === f);
          }});
        }});
      }});
    }})();
    </script>
</body>
</html>
"""


def build_index(essays_by_slug, notes_by_id):
    """Render the topic-grouped writing index. Returns (filters_html, groups_html):
    color-coded filter chips up top, plus each topic wrapped in a .wgroup that the
    chips show/hide. Essays + notes are intermixed per topic, newest-first, each
    tagged with a format badge."""
    # Coverage guard: every curated piece filed under exactly one topic, nothing stray.
    keys = [k for *_, ks in TOPICS for k in ks]
    dupes = sorted({k for k in keys if keys.count(k) > 1})
    if dupes:
        raise SystemExit(f"pieces filed under multiple topics: {dupes}")
    expected = set(essays_by_slug) | set(NOTE_TITLES)
    missing = sorted(expected - set(keys))
    extra = sorted(set(keys) - expected)
    if missing:
        raise SystemExit(f"curated pieces not assigned to a topic: {missing}")
    if extra:
        raise SystemExit(f"topic keys not in any curated list: {extra}")

    chips = ['            <button class="wfilter is-active" data-filter="all">All</button>']
    groups = []
    for label, slug, color, ks in TOPICS:
        chips.append(
            f'            <button class="wfilter" data-filter="{escq(slug)}" '
            f'style="--c:{escq(color)}"><span class="wdot"></span>{esc(label)}</button>'
        )
        items = []
        for k in ks:
            if k in essays_by_slug:
                p = essays_by_slug[k]
                items.append(("essay", f"{k}.html", p["title"], p["date"], p["baseScore"]))
            else:
                t = notes_by_id[k]
                items.append(("note", f"shortform.html#{k}", NOTE_TITLES[k],
                              (t.get("postedAt") or "")[:10], t.get("baseScore", 0)))
        items.sort(key=lambda i: i[3], reverse=True)
        rows = [f'                <h2 class="wtopic">{esc(label)}</h2>']
        for kind, href, title, date, karma in items:
            rows.append(
                f'                <a class="wrow" href="{escq(href)}">'
                f'<span class="wbadge {kind}">{kind}</span>'
                f'<span class="wdate">{MONTHS[int(date[5:7])]} {date[:4]}</span>'
                f'<span class="wtitle">{esc(title)}</span>'
                f'<span class="wkarma">{karma} karma</span></a>'
            )
        groups.append(
            f'            <section class="wgroup" data-topic="{escq(slug)}" '
            f'style="--c:{escq(color)}">\n' + "\n".join(rows) + "\n            </section>"
        )
    return "\n".join(chips), "\n".join(groups)


def build():
    archive = {p["slug"]: p for p in json.loads(ARCHIVE.read_text(encoding="utf-8"))}
    posts = []
    for slug in CURATED:
        if slug not in archive:
            raise SystemExit(f"curated slug not in archive: {slug}")
        p = archive[slug]
        p["title"] = (p.get("title") or "").strip()
        p["date"] = p["postedAt"][:10]
        p["out"] = f"{slug}.html"
        posts.append(p)

    for p in posts:
        y, m, _ = p["date"].split("-")
        html = PAGE.format(
            title=esc(p["title"]),
            lw_url=escq(p["pageUrl"]),
            eyebrow=f"essay · {MONTHS[int(m)]} {y}",
            date_long=date_long(p["date"]),
            karma=p["baseScore"],
            body=prepare_body(p["htmlBody"]),
        )
        (OUT / p["out"]).write_text(html, encoding="utf-8")

    notes_by_id = {t["_id"]: t for t in json.loads(SHORTFORM_ARCHIVE.read_text(encoding="utf-8"))}
    essays_by_slug = {p["slug"]: p for p in posts}
    filters, rows = build_index(essays_by_slug, notes_by_id)
    (OUT / "index.html").write_text(
        INDEX.format(filters=filters, rows=rows), encoding="utf-8")

    update_homepage(posts[:HOMEPAGE_N])

    print(f"Built {len(posts)} post pages + index.html in {OUT}/")
    for p in posts:
        print(f"  writing/{p['out']}")


def update_homepage(featured):
    """Fill the homepage #writing region (in index.template.html) with the most
    recent curated posts. build.py renders index.html from the template after."""
    rows = "\n".join(
        f'                    <a href="writing/{escq(p["out"])}">\n'
        f'                        <span>{esc(p["title"])}</span>'
        f'<span class="arr">→</span></a>'
        for p in featured
    )
    tpl = HOME_TEMPLATE.read_text(encoding="utf-8")
    pat = re.compile(re.escape(HOME_BEGIN) + r".*?" + re.escape(HOME_END), re.DOTALL)
    if not pat.search(tpl):
        raise SystemExit("homepage-writing sentinels not found in index.template.html")
    block = f"{HOME_BEGIN}\n{rows}\n                    {HOME_END}"
    HOME_TEMPLATE.write_text(pat.sub(lambda _: block, tpl), encoding="utf-8")
    print(f"Updated homepage #writing with {len(featured)} most-recent posts "
          f"(re-run build.py to regenerate index.html):")
    for p in featured:
        print(f"  {p['date']}  {p['title']}")


if __name__ == "__main__":
    build()
